# Generated by Django 5.0.6 on 2026-04-26 17:30

import django.core.validators
import envios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encomienda',
            name='empleado_registro',
        ),
        migrations.RemoveField(
            model_name='historialestado',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='historialestado',
            name='encomienda',
        ),
        migrations.AlterModelOptions(
            name='encomienda',
            options={'ordering': ['-fecha_envio'], 'verbose_name': 'Encomienda', 'verbose_name_plural': 'Encomiendas'},
        ),
        migrations.RenameField(
            model_name='encomienda',
            old_name='fecha_registro',
            new_name='fecha_envio',
        ),
        migrations.RemoveField(
            model_name='encomienda',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='encomienda',
            name='fecha_entrega_est',
        ),
        migrations.RemoveField(
            model_name='encomienda',
            name='fecha_entrega_real',
        ),
        migrations.RemoveField(
            model_name='encomienda',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='encomienda',
            name='remitente',
        ),
        migrations.RemoveField(
            model_name='encomienda',
            name='ruta',
        ),
        migrations.RemoveField(
            model_name='encomienda',
            name='volumen_cm3',
        ),
        migrations.AddField(
            model_name='encomienda',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, validators=[envios.validators.validar_codigo_encomienda]),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('TR', 'En tránsito'), ('EN', 'Entregado'), ('DE', 'Devuelto')], default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='peso_kg',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[envios.validators.validar_peso_positivo, django.core.validators.MinValueValidator(0.01, message='El peso mínimo es 0.01 kg')]),
        ),
        migrations.AlterModelTable(
            name='encomienda',
            table=None,
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='HistorialEstado',
        ),
    ]
